env:
  - GO111MODULE=on
before:
  hooks:
  - go mod download
builds:
  -
    id: "magicwand"
    binary: magicwand
    ldflags: -s -w -X main.Version={{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: default
    builds:
      - magicwand
    replacements:
      386: i386
      amd64: x86_64

nfpms:
  -
    builds:
    - magicwand

    vendor: muesli
    homepage: "https://fribbledom.com/"
    maintainer: "Christian Muehlhaeuser <muesli@gmail.com>"
    description: "MagicWand makes your input devices context sensitive"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

signs:
  - artifacts: checksum

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
